// backend/src/models/InsurancePartner.js
import mongoose from "mongoose";

/**
 * InsurancePartner
 * - Dashboard creates partners (Option A: partnerCode field)
 * - Backend historically used `code`
 * - We now support BOTH:
 *    partnerCode <-> code (kept in sync)
 */
const InsurancePartnerSchema = new mongoose.Schema(
  {
    /**
     * ✅ NEW (Option A)
     * The dashboard sends partnerCode (e.g. ABC, OUTSURANCE, DISCOVERY)
     * This is the primary identifier for reporting and code generation.
     */
    partnerCode: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      unique: true,
      index: true,
    },

    /**
     * ✅ Legacy field (older systems)
     * Still kept for compatibility.
     * Will be auto-filled from partnerCode if missing.
     */
    code: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      unique: true,
      index: true,
    },

    // Display name shown in app/dashboard
    name: {
      type: String,
      required: true,
      trim: true,
    },

    // Optional brand logo
    logoUrl: {
      type: String,
      default: "",
      trim: true,
    },

    /**
     * ✅ Legacy single-country field (optional)
     * Kept for compatibility with older dashboard calls.
     */
    countryCode: {
      type: String,
      default: null,
      trim: true,
      uppercase: true,
      index: true,
    },

    // Which countries this insurance is available in (multi-country routing)
    countryCodes: {
      type: [String],
      default: ["ZA"],
      set: (arr) =>
        Array.isArray(arr)
          ? arr.map((x) => String(x).trim().toUpperCase()).filter(Boolean)
          : ["ZA"],
      index: true,
    },

    // If disabled, app should not show it
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    /**
     * Billing model:
     * - insurance jobs are NOT paid immediately by customer
     * - partner is invoiced monthly based on usage
     */
    billing: {
      billingType: {
        type: String,
        enum: ["MONTHLY_INVOICE"],
        default: "MONTHLY_INVOICE",
      },

      // Optional contract terms
      contractStartDate: { type: Date, default: null },
      contractEndDate: { type: Date, default: null },

      // If you want per-partner markup/discount later
      rateMultiplier: {
        type: Number,
        default: 1,
        min: 0,
      },

      // VAT/tax rules (country-specific handling later)
      vatNumber: { type: String, default: "", trim: true },
      taxPercentage: { type: Number, default: 0, min: 0, max: 100 },
    },

    /**
     * Contact info for invoicing / support
     */
    contact: {
      email: { type: String, default: "", trim: true, lowercase: true },
      phone: { type: String, default: "", trim: true },
      contactPerson: { type: String, default: "", trim: true },
    },

    /**
     * ✅ Additional flat fields (dashboard legacy)
     * These are NOT required, but we support them and sync into contact.*
     */
    contactEmail: { type: String, default: null, trim: true, lowercase: true },
    contactPhone: { type: String, default: null, trim: true },
    billingEmail: { type: String, default: null, trim: true, lowercase: true },

    /**
     * Partner settings
     */
    settings: {
      // If true: only codes generated by TowMech system can be used
      requireCode: { type: Boolean, default: true },

      // If true: code must match selected insurance partner
      strictPartnerMatch: { type: Boolean, default: true },

      // How long codes remain valid
      codeValidityDays: { type: Number, default: 30, min: 1, max: 3650 },

      // Rate limiting per code (optional)
      maxJobsPerCode: { type: Number, default: 1, min: 1 },
    },

    /**
     * Audit fields
     */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  { timestamps: true }
);

/**
 * ✅ Normalize + sync compatibility fields BEFORE validation
 * (so required fields can be auto-filled)
 */
InsurancePartnerSchema.pre("validate", function (next) {
  // partnerCode <-> code
  if (this.partnerCode) {
    this.partnerCode = String(this.partnerCode).trim().toUpperCase();
  }
  if (this.code) {
    this.code = String(this.code).trim().toUpperCase();
  }

  if (!this.partnerCode && this.code) this.partnerCode = this.code;
  if (!this.code && this.partnerCode) this.code = this.partnerCode;

  // name trim
  if (this.name) this.name = String(this.name).trim();

  // country normalization
  if (this.countryCode) this.countryCode = String(this.countryCode).trim().toUpperCase();

  if (Array.isArray(this.countryCodes)) {
    this.countryCodes = this.countryCodes
      .map((c) => String(c).trim().toUpperCase())
      .filter(Boolean);
    if (this.countryCodes.length === 0) this.countryCodes = ["ZA"];
  } else {
    this.countryCodes = ["ZA"];
  }

  // countryCode <-> countryCodes[0]
  if (this.countryCode && !this.countryCodes.includes(this.countryCode)) {
    this.countryCodes = Array.from(new Set([...this.countryCodes, this.countryCode]));
  }
  if (!this.countryCode && this.countryCodes.length > 0) {
    this.countryCode = this.countryCodes[0];
  }

  // contactEmail/contactPhone sync with contact.*
  if (typeof this.contactEmail === "string" && this.contactEmail.trim()) {
    this.contactEmail = this.contactEmail.trim().toLowerCase();
    if (!this.contact) this.contact = {};
    if (!this.contact.email) this.contact.email = this.contactEmail;
  }

  if (typeof this.contactPhone === "string" && this.contactPhone.trim()) {
    this.contactPhone = this.contactPhone.trim();
    if (!this.contact) this.contact = {};
    if (!this.contact.phone) this.contact.phone = this.contactPhone;
  }

  // If contact.* exists but flat fields missing, populate flat fields too
  if (this.contact?.email && !this.contactEmail) {
    this.contactEmail = String(this.contact.email).trim().toLowerCase();
  }
  if (this.contact?.phone && !this.contactPhone) {
    this.contactPhone = String(this.contact.phone).trim();
  }

  // billingEmail normalize
  if (typeof this.billingEmail === "string" && this.billingEmail.trim()) {
    this.billingEmail = this.billingEmail.trim().toLowerCase();
  }

  next();
});

const InsurancePartner =
  mongoose.models.InsurancePartner ||
  mongoose.model("InsurancePartner", InsurancePartnerSchema);

export default InsurancePartner;